// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ConnectionStatusController from "./connection_status_controller"
import MobileMenuController from "./mobile_menu_controller"
import ImageRefreshController from "./image_refresh_controller"
import DateNavigationController from "./date_navigation_controller"
import ForecastToggleController from "./forecast_toggle_controller"
import WeatherUpdateController from "./weather_update_controller"
import LineGraphController from "./line_graph_controller"

application.register("hello", HelloController)
application.register("connection-status", ConnectionStatusController)
application.register("mobile-menu", MobileMenuController)
application.register("image-refresh", ImageRefreshController)
application.register("traffic-cameras", ImageRefreshController)
application.register("date-navigation", DateNavigationController)
application.register("forecast-toggle", ForecastToggleController)
application.register("weather-update", WeatherUpdateController)
application.register("line-graph", LineGraphController)
