---
Aqi:
  observed_at:
    ColumnPresenceChecker:
      enabled: false
  pm2_5:
    ColumnPresenceChecker:
      enabled: false
  source:
    ColumnPresenceChecker:
      enabled: false
Earthquake:
  depth:
    ColumnPresenceChecker:
      enabled: false
  distance:
    ColumnPresenceChecker:
      enabled: false
  eventtime:
    ColumnPresenceChecker:
      enabled: false
  index_earthquakes_on_usgs_id:
    UniqueIndexChecker:
      enabled: false
  last_updated:
    ColumnPresenceChecker:
      enabled: false
  lat:
    ColumnPresenceChecker:
      enabled: false
  lon:
    ColumnPresenceChecker:
      enabled: false
  magnitude:
    ColumnPresenceChecker:
      enabled: false
  place:
    ColumnPresenceChecker:
      enabled: false
  revised:
    ThreeStateBooleanChecker:
      enabled: false
  url:
    ColumnPresenceChecker:
      enabled: false
  usgs_id:
    ColumnPresenceChecker:
      enabled: false
Forecast:
  forecast:
    ColumnPresenceChecker:
      enabled: false
ReportEntry:
  index_report_entries_on_report_id:
    RedundantIndexChecker:
      enabled: false
WeatherMeasurement:
  index_weather_measurements_on_reading_date_time:
    UniqueIndexChecker:
      enabled: false
  rain_day:
    ColumnPresenceChecker:
      enabled: false
