#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">
	<p>Positioned on Lea Hill in Auburn, WA, this weather station is powered by an Ambient Weather WS-2902C. Data samples are taken every 5 seconds and published live to this site.
	</p>
	<p>
	This station tracks the following weather measurements:
		<ul>
			<li>Temperature</li>
			<li>Humidity</li>
			<li>Barometric pressure</li>
			<li>Wind
			<ul>
				<li>Direction</li>
				<li>Speed</li>
			</ul></li>
			<li>Rainfall</li>
			<li>UV</li>
		</ul>
	</p>
	<p>
	Everything else is recorded and interpolated using software.
	</p>
	<h3>Support</h3>
	<p>If you find this site and its data helpful, consider <a href="https://buymeacoffee.com/johnathan">buying me a coffee</a> in return.</a>
	</p>

	<h3>Weather Station Data Services</h3>
	<p>
		Data from this station is syndicated to the following services:
		<ul>
			<li>Weather Underground - <a href="https://www.wunderground.com/weather/us/wa/auburn/KWAAUBUR154?ref=leahillwxdotorg" target="_blank">KWAAUBU154</a></li>
			<li>PWS Weather - <a href="https://www.pwsweather.com/station/pws/S50LEAHILL?ref=leahillwxdotorg" target="_blank">S50LEAHILL</a></li>
			<li>AWEKAS - <a href="https://www.awekas.at/en/station.php?id=21599&ref=leahillwxorg" target="_blank">S50LEAHILL</a></li>
			<li>Weathercloud - <a href="https://app.weathercloud.net/d7373931868#profile?ref=leahillwxdotorg" target="_blank">S50LEAHILL</a></li>
			<li>CWOP - <a href="http://www.findu.com/cgi-bin/wxpage.cgi?last=24&call=GW1125&ref=leahillwxorg" target="_blank">GW1125</a></li>
			
		</ul>
	</p>
	<h3>Other Links</h3>
	<p>
		<ul>
			<li><a href="https://www.weather.gov/sew/?ref=leahillwxdotorg" target="_blank">Local National Weather Service office</a>
		</ul>
	</p>
	
	<h3>Getting in Touch</h3>
	<p>Feel free to reach out to me through one of the following channels:<p>
		<ul>
			<li>Email: email at johnathan dot org</li>
			<li>Twitter: <a href="//twitter.com/_johlym">@_johlym</a></li>
		</ul>
	</p>
	<h3>Technical details</h3>
	<p>
		<ul>
			<li>Weather station: <a href="https://www.amazon.com/Ambient-Weather-WiFi-Station/dp/B01N5TEHLI?crid=2L5G3GT84KF1K&keywords=Ambient+Weather+WS-2902c&qid=1641682704&sprefix=ambient+weather+ws-2902c%2Caps%2C128&sr=8-5&linkCode=ll1&tag=johnatlymanco-20&linkId=d126460e7d0be733a4492e1bd2fddbbc&language=en_US&ref_=as_li_ss_tl" target="_blank">Ambient Weather WS-2902C</a></li>
			<li>Data capture: <a href="https://www.amazon.com/Ecowitt-Temperature-Humidity-Atmospheric-Pressure/dp/B0978XLG8T?crid=2F8XNMZMQTLO6&keywords=Ecowitt%2BGW1000&qid=1641682759&sprefix=ecowitt%2Bgw1000%2Caps%2C124&sr=8-3&th=1&linkCode=ll1&tag=johnatlymanco-20&linkId=fd92640703c077e14bb732f70d1ff153&language=en_US&ref_=as_li_ss_tl" target="_blank">Ecowitt GW11000</a></li>
			<li>Data archive and site generation: <a href="https://weewx.com/?ref=leahillwxorg" target="_blank">WeeWX</a></li>
			<li>Charting: <a href="http://www.highcharts.com/?ref=leahillwxorg" target="_blank">HighCharts</a></li>
			<li>WeeWx Skin: <a href="https://github.com/poblabs/weewx-belchertown" target="_blank">Belchertown</a></li>
			<li>Hosting: <a href="https://www.linode.com/?r=2527e12c0aed087cbe51d3862f0a6bb6c5ab8f9a" target="_blank">Linode</a> (get a $100 credit with this link)</li>
		</ul>
	</p>
	<hr>
	<p>Some semi-relevant details:
		<ul>
			<li>Server uptime: $station.os_uptime</li>
			<li>WeeWX uptime: $station.uptime</li>
			<li>WeeWX version: $station.version</li>
			<li>Skin Version: $belchertown_version</li>
		</ul>
	</p>
	<p>
	Disclosure: This page may contain affiliate links. At no cost to you, making a purchase using those links may result in an earned commission for the owner and maintainer of this site, which helps fund this project.
	</p>
</div>
