download_open_weather_forecast_job:
  cron: "every 10 minutes"
  class: "DownloadOpenWeatherForecastJob"

download_open_weather_aqi_job:
  cron: "every 10 minutes"
  class: "DownloadOpenWeatherAqiJob"

download_latest_earthquake_job:
  cron: "every 1 minute"
  class: "DownloadLatestEarthquakeJob"

delete_old_forecasts_job:
  cron: "every 1 day"
  class: "DeleteOldForecastsJob"

update_third_party_weather_platforms_job:
  cron: "every 15 seconds"
  class: "UpdateThirdPartyWeatherPlatformsJob"

generate_report_job:
  cron: "every 12:01 AM in America/Los_Angeles"
  class: "GenerateReportJob"
  description: "Generate daily climatological report entry at 12:01 AM"

generate_hourly_report_job:
  cron: "every hour in America/Los_Angeles"
  class: "GenerateHourlyReportJob"
  description: "Generate hourly climatological report entry at 1 minute past each hour"

generate_year_records_job:
  cron: "every 12:02 AM in America/Los_Angeles"
  class: "GenerateYearRecordsJob"
  description: "Calculate and update records for current year at 12:02 AM"

generate_all_time_records_job:
  cron: "every 12:06 AM in America/Los_Angeles"
  class: "GenerateAllTimeRecordsJob"
  description: "Calculate and update all-time records at 12:06 AM"
