download_open_weather_forecast_job:
  cron: "*/2 * * * *"
  class: "DownloadOpenWeatherForecastJob"
  description: "Download forecast every 2 minutes"

download_open_weather_aqi_job:
  cron: "0 * * * *"
  class: "DownloadOpenWeatherAqiJob"
  description: "Download air quality every hour at the top of the hour"

download_latest_earthquake_job:
  cron: "* * * * *"
  class: "DownloadLatestEarthquakeJob"
  description: "Download earthquake data every minute"

delete_old_forecasts_job:
  cron: "0 11 * * *"
  class: "DeleteOldForecastsJob"
  description: "Delete old forecasts daily at 11:00 AM UTC (3:00 AM PST)"

update_third_party_weather_platforms_job:
  cron: "*/15 * * * * *"
  class: "UpdateThirdPartyWeatherPlatformsJob"
  description: "Update third-party platforms every 15 seconds"

generate_report_job:
  cron: "1 8 * * *"
  class: "GenerateReportJob"
  description: "Generate daily report at 8:01 AM UTC (12:01 AM PST)"

generate_hourly_report_job:
  cron: "1 * * * *"
  class: "GenerateHourlyReportJob"
  description: "Generate hourly report at 1 minute past each hour"

generate_year_records_job:
  cron: "2 8 * * *"
  class: "GenerateYearRecordsJob"
  description: "Calculate year records at 8:02 AM UTC (12:02 AM PST)"

generate_all_time_records_job:
  cron: "6 8 * * *"
  class: "GenerateAllTimeRecordsJob"
  description: "Calculate all-time records at 8:06 AM UTC (12:06 AM PST)"
